name: Build DLL

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc

    steps:

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-pc-windows-msvc
            i686-pc-windows-msvc

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: rustdeskid-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*.dll
