name: Build DLL

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            arch: x64
            triplet: x64-windows-static

          - target: i686-pc-windows-msvc
            arch: x86
            triplet: x86-windows-static

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: lukka/run-vcpkg@v11

      - name: Install vcpkg packages
        shell: pwsh
        run: |
          vcpkg install libsodium:${{ matrix.triplet }}

      - uses: Swatinem/rust-cache@v2

      - name: Build
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
          VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}
        run: cargo build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: rustdeskid-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/*.dll
